services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: finagentics:latest
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
